
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnqrqjhtvjcjjvshoykv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBucXJxamh0dmpjamp2c2hveWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MDc2MjIsImV4cCI6MjA1OTI4MzYyMn0.8vD0Ad99zhAC9RyEVqIn-h4MItYeoww-xeHhnyK_1M4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
