// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxfkerzlhukixngzpcho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4ZmtlcnpsaHVraXhuZ3pwY2hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1ODU4NjksImV4cCI6MjA1OTE2MTg2OX0.4mHjs_59IjqOZFEuY_Muzi8AvhEhvFnxB6-010arDSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);